from python:latest
RUN mkdir /app
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
RUN apt-get update
RUN apt-get install gdal-bin
RUN python manage.py shell < mqtt/aysinc_functions/functions.py
CMD ["python", "manage.py", "runserver"]