# Generated by Django 4.1.6 on 2024-07-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_device_device_motor_devicetype_and_more'),
        ('versions', '0006_alter_version_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='device_version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hall.devicetype'),
            preserve_default=False,
        ),
    ]
