# Generated by Django 4.1.6 on 2023-02-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.CharField(max_length=255)),
                ('receive_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hall.head')),
            ],
        ),
    ]
