# Generated by Django 4.1.6 on 2023-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.CharField(max_length=500)),
                ('mac_address', models.CharField(max_length=500)),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
    ]
