# Generated by Django 4.1.6 on 2023-04-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_head_head_code_alter_head_unique_together'),
        ('device', '0002_tempdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headdata',
            name='head',
        ),
        migrations.AddField(
            model_name='headdata',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hall.device'),
            preserve_default=False,
        ),
    ]
