# Generated by Django 4.1.6 on 2023-03-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceparameter',
            name='address',
            field=models.IntegerField(default=120, max_length=511),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headparameter',
            name='main_add',
            field=models.IntegerField(default=120, max_length=511),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headparameter',
            name='sub_add',
            field=models.IntegerField(default=120, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviceparameter',
            name='value',
            field=models.IntegerField(max_length=65545),
        ),
        migrations.AlterField(
            model_name='headparameter',
            name='value',
            field=models.IntegerField(max_length=65545),
        ),
    ]
