# Generated by Django 4.1.6 on 2024-07-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0002_deviceparameter_address_headparameter_main_add_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chip_id', models.CharField(max_length=255)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='headparameter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='headparameter',
            name='head',
        ),
        migrations.DeleteModel(
            name='DeviceParameter',
        ),
        migrations.DeleteModel(
            name='HeadParameter',
        ),
    ]
