# Generated by Django 4.1.6 on 2024-08-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0008_remove_device_device_motor_device_command_and_more'),
        ('parameter', '0003_parameter_alter_headparameter_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='chip_id',
        ),
        migrations.AddField(
            model_name='parameter',
            name='device_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hall.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='name',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('valid_types', models.JSONField(max_length=100)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.devicetype')),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='parameter_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='parameter.parametertype'),
            preserve_default=False,
        ),
    ]
