# Generated by Django 4.1.6 on 2024-08-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0008_remove_device_device_motor_device_command_and_more'),
        ('parameter', '0004_remove_parameter_chip_id_parameter_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='device_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hall.device'),
        ),
    ]
