# Generated by Django 4.1.6 on 2023-02-09 09:25

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='company name', max_length=255)),
                ('p_name', models.CharField(help_text='persian company name', max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('expire_service_time', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام سالن', max_length=500)),
                ('capacity', models.IntegerField(blank=True, help_text='ظرفیت سالن', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='موقعیت مکانی', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ آپدیت')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.company')),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chip_ip', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ آپدیت')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.production')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('one', 'One Motor'), ('two', 'Two Motor')], default='one', max_length=255)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.group')),
            ],
        ),
    ]
