# Generated by Django 4.1.6 on 2023-03-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head',
            name='chip_ip',
        ),
        migrations.AddField(
            model_name='device',
            name='chip_ip',
            field=models.CharField(default=123456879, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
