# Generated by Django 4.1.6 on 2023-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_remove_head_chip_ip_device_chip_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='head_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='head',
            unique_together={('head_code', 'device')},
        ),
    ]
