# Generated by Django 4.1.6 on 2024-07-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_head_head_code_alter_head_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='production',
        ),
        migrations.AddField(
            model_name='squad',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hall.company'),
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
    ]
