# Generated by Django 4.1.6 on 2023-02-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_rename_group_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hall.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='head',
            name='chip_ip',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
