# Generated by Django 4.1.6 on 2024-07-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_remove_production_hall_remove_squad_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_motor',
            field=models.CharField(choices=[('one', 'One Motor'), ('two', 'Two Motor')], default='one', max_length=255),
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.company')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.devicetype'),
        ),
    ]
