# Generated by Django 4.1.6 on 2024-07-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_device_device_motor_devicetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hall.company'),
            preserve_default=False,
        ),
    ]
