# Generated by Django 4.1.6 on 2024-07-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0003_parameter_alter_headparameter_unique_together_and_more'),
        ('hall', '0006_alter_squad_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='company',
        ),
        migrations.DeleteModel(
            name='Head',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='company',
            field=models.ManyToManyField(to='hall.company'),
        ),
    ]
