# Generated by Django 4.1.6 on 2024-08-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0007_remove_devicetype_company_delete_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_motor',
        ),
        migrations.AddField(
            model_name='device',
            name='command',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
