# Generated by Django 4.1.6 on 2024-08-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0008_remove_device_device_motor_device_command_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='chip_ip',
            new_name='chip_id',
        ),
    ]
