# Generated by Django 4.1.6 on 2024-08-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0009_rename_chip_ip_device_chip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='chip_id',
            new_name='chip_ip',
        ),
    ]
