four_option_in_permission = {
    "add": "اضافه کردن",
    "change": "تغییر دادن",
    "delete": "حذف کردن",
    "view": "نمایش دادن",
}

can = {"Can": "دسترسی"}

filtered_permissions = {
    'layers': {'models': {'layer': 'لایه', 'lcategory': 'دسته بندی لایه', 'attribute': 'فیلد'}, 'translate': 'لایه ها'},
    'account': {'models': {'user': 'کاربر', 'profile': 'پروفایل', 'loginuser': 'کاربر لاگین کرده',
                           'DataBaseUser': 'کاربر دیتابیس'}, 'translate': 'کابران'},
    'analyse': {'models': {'analyse': 'آنالیز', }, 'translate': 'آنالیز'},
    'api_keys': {'models': {'apikeys': 'کلید دسترسی', }, 'translate': 'کلید دسترسی'},
    'basemaps': {'models': {'basemap': 'نقشه زیرین', }, 'translate': 'نقشه های زیرین'},
    'bookmark': {'models': {'bookmark': 'نشانک', }, 'translate': 'نشانک'},
    'connections': {'models': {'apiprofile': 'پروفایل API', 'databaseprofile': 'پروفایل پایگاه داده',
                               'owsprofile': 'پروفایل سرویس'}, 'translate': 'پروفایل اتصالات'},
    'documents': {'models': {'category': 'دسته بندی', 'file': 'فایل'}, 'translate': 'مستندات'},
    'fences': {'models': {'fence': 'محدود جغرافیایی'}, 'translate': 'محدوده های جغرافیایی'},
    'forms': {'models': {'form': 'فرم', 'constant': 'ثابت'}, 'translate': 'فرم ها'},
    'global_settings': {'models': {'globalpermission': 'دسترسی های عمومی', 'globalsettings': 'تنظیمات عمومی'},
                        'translate': 'عمومی'},
    'layerstyles': {'models': {'style': 'کارتوگرافی'}, 'translate': 'کارتوگرافی لایه'},
    'mail': {'models': {'smtpserverconfig': 'تنظیمات mail سرور'}, 'translate': 'ایمیل'},
    'map': {'models': {'map': 'نقشه'}, 'translate': 'نقشه ها'},
    'markers': {'models': {'marker': 'نماد'}, 'translate': 'نماد ها'},
    'networkanalysis': {'models': {'network': 'آنالیز شبکه'}, 'translate': 'آنالیز شبکه'},
    'panorama': {'models': {'publisheddirectory': 'پوشه های انتشار یافته'}, 'translate': 'پاناروما'},
    'relates': {'models': {'apirelation': 'اتصال API', 'tablerelation': 'اتصال پایگاه داده'}, 'translate': 'اتصالات'},
    'roles': {'models': {'role': 'چارت سازمانی'}, 'translate': 'چارت سازمانی'},
    'audit': {'models': {'project': 'پروژه ی ممیزی', 'basemapproject': 'نقشه های زیرین پروژه',
                         'helperlayerproject': 'لایه های کمکی پروژه', 'userproject': 'کاربران ممیزی',
                         'operation': 'کارتابل', 'operationfile': 'فایل های ممیزی'}, 'translate': 'ممیزی'},
    'tables': {'models': {'table': 'جدول'}, 'translate': 'جداول'},
    'tasks': {'models': {'task': 'تسک پشت زمینه'}, 'translate': 'تسک های پشت زمینه'},
    'nda': {'models': {'nda': 'توافق نامه'}, 'translate': 'توافق نامه'},
    'admin': {'models': {'logentry': 'لاگ'}, 'translate': 'مدیریت'},
    'print': {'models': {'jsonmodel': 'اضافه کردن temp'}, 'translate': 'چاپ'},
    'cartable': {'models': {'cartable': 'کارتابل'}, 'translate': 'کارتابل'},
    'workflow': {'models': {'workflow': 'جریان', 'state': 'گره'}, 'translate': 'جریان'},
    'backup_restore': {'models': {'backupschedule': 'زمان بندی های پشتیبانی گیری',
                                  'backupplan': 'برنامه های پشتیبانی گیری',
                                  'takenbackup': 'پشتیبان گیری های انجام شده',
                                  }, 'translate': 'پشتیبانی گیری'},
}

model_name_mapper = {
    "log entry": "نمایش لاگ",
    "group": "گروه",
    "permission": "دسترسی",
    "content type": "محتوا",
    "group object permission": "دسترسی های محتوایی گروه",
    "user object permission": "دسترسی های محتوایی کاربر",
    "company": "کارخانه",
    "hall": "سالن",
    "device": "دستگاه",
    "production": "خط تولید",
    "head": "هد",
    "user": "کاربر",
    "squad": "تیم",
}

spatial_permissions = {
    'Can upload bulk file': 'آپلود دسته جمعی فایل',
    'Can download file': 'دانلود فایل',
    'Can assign permission to other': 'دسترسی دادن به دیگران',
    'Can copy permission': 'کپی دسترسی ها',
    'is manager system': 'مدیر سامانه',
    'Can add relation': 'اضافه کردن اتصالات',
    'Can clone layer': 'کپی گرفتن لایه',
    'Can convert layer': 'تبدیل لایه',
    'Can copy permission layer': 'کپی دسترسی های لایه',
    'Can copy style': 'کپی کارتوگرافی',
    'Can export layer': 'خروجی گرفتن از لایه',
    'Can join layer': 'join روی لایه',
    'Can topology layer': 'توپولوژی روی لایه',
    'Can View Panorama': 'نمایش پاناروما',
    'Can View Panorama Directory': 'نمایش پوشه های پاناروما',
    'Can View login user': 'نمایش کاربرهای لاگین کرده',
    'Can Take Print': 'چاپ کردن',
    'Can Restore Backup': 'انجام فرایند بازیابی اطلاعات',
}
